{% set name = "starsessions" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starsessions-{{ version }}.tar.gz
  sha256: e9e06ccca176f0e40deac11e7a6cb8ec48bdd3b1a214f847be501c4b5296e4ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - itsdangerous >=2.0.0,<3.0.0
    - python >=3.8,<4.0
    - starlette

test:
  imports:
    - starsessions
  commands:
    - pip check
  requires:
    - aioredis >=2.0.0
    - redis-py
    - pip

about:
  home: https://github.com/alex-oleshkevich/starsessions
  summary: Pluggable session support for Starlette.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
