{% set name = "starsessions" %}
{% set version = "2.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starsessions-{{ version }}.tar.gz
  sha256: 7e028b7b06a5b7f8ac4fe7894eb609941f96d137bc9d6cc6b6d86ae4724d7e36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8.0,<4.0.0
  run:
    - itsdangerous >=2.0.1,<3.0.0
    - python >=3.8.0,<4.0.0
    - starlette >=0,<1

test:
  imports:
    - starsessions
  commands:
    - pip check
  requires:
    - aioredis >=2.0.0
    - redis-py
    - pip

about:
  home: https://github.com/alex-oleshkevich/starsessions
  summary: Pluggable session support for Starlette.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
