{% set name = "starsessions" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starsessions-{{ version }}.tar.gz
  sha256: 8d3b509d4e6d235655f7dd495fcf0afc1bd86da84de3a8d434e6f82137ebcde8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6.2
  run:
    - itsdangerous >=2.0.1
    - python >=3.6.2
    - starlette >=0

test:
  imports:
    - starsessions
    - starsessions.backends
  commands:
    - pip check
  requires:
    - aioredis >=2.0.0
    - pip

about:
  home: https://github.com/alex-oleshkevich/starsessions
  summary: Pluggable session support for Starlette.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
